### ISSUE TITLE
 Apache stuck with AH00094: Command line: 'apache2 -D FOREGROUND'

### ISSUE THREAD

**Issue by tobiolalusi** [docker-library/php#1004]
My initial download of the php-7.2-apache image was about 4 days ago, with apache still running smoothly, until I redownloaded the image again yesterday and then apache gets stuck with this error:
```
[mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.2.30 configured -- resuming normal operations
[core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Below is my Dockerfile:
```
FROM php:7.2-apache

# ...
# non-apache-related apt installs
# ...

# apache config
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN echo "ServerName myappondocker.local" >> /etc/apache2/apache2.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN a2enmod rewrite headers

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

ARG uid
RUN useradd -G www-data,root -u $uid -d /home/myapp myapp
RUN mkdir /home/myapp && \
    chown -R myapp:myapp /home/myapp
```
And below is also my docker-compose for this service:
```
version: '3.5'

services:
  myapp:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: myapp
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - ${HOST_PORT}:80
    networks:
      backend:
        aliases:
          - myapp
```
