### ISSUE TITLE
RUN useradd with ENV variable fails

### ISSUE THREAD

**Issue by evs-xsarus** [docker-library/php#1067]
Using docker compose and a docker file I can add a user for use with composer:

_docker-compose.yml_
```yml
version: "3.7"
services:
  phpcli74:
    image: php:7.4-cli
    user: "${DOCKER_UID}:${DOCKER_GID}"
    environment:
      - COMPOSER_CACHE_DIR=/home/dockeruser/.composer
      - DOCKER_UID=${DOCKER_UID}
      - DOCKER_GID=${DOCKER_GID}
    build:
      context: .
      dockerfile: Dockerfile_php-cli
```

_Dockerfile_php-cli_
```yml
FROM php:7.4-cli

RUN useradd dockeruser

## composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer
```

I run docker-compose as follows:

```DOCKER_UID=$(id -u $USER) DOCKER_GID=$(id -g $USER) docker-compose up -d```

The user 'dockeruser' is created with uid 1000, this works fine as long as the host also has uid 1000. To avoid this issue, I want to set the user dynamically. In the Docker file, the useradd is this changed to:

`RUN useradd -u${DOCKER_UID} -g${DOCKER_GID} dockeruser`

Now, `docker-compose up -d` fails with:
> Service 'phpcli74' failed to build : The command '/bin/sh -c useradd -u${DOCKER_UID} -g${DOCKER_GID} dockeruser' returned a non-zero code: 3

I can't figure out the syntax to make this work, any ideas?
