### ISSUE TITLE
File system operations don't work

### ISSUE THREAD

**Issue by andreasmhahn** [docker-library/php#1083]
When using file system operations like scandir(); or readdir(); on php-fpm (tested with php 8rc and php 7), the return values/array are empty. Tested with file mount on host system.

**Comment by yosifkit** [comment]
Is this Docker-for-Mac/Docker-for-Windows or which Linux distribution release? What is the `docker run` command and any other steps done?

---

Just a guess that it is likely permissions; what is the output `ls -la` from the container and from the host?  By default, `php-fpm` will run as the `www-data` user in the container, so it may not have access to the host folder. To change the user, just user the `docker run` flag: `--user 1000:1000` (or whatever user ID you need).

https://github.com/docker-library/docs/tree/c7284b20ae4b6f8b791bfa6ca9a25b1e1cb0666e/php#running-as-an-arbitrary-user

**Comment by andreasmhahn** [comment]
I am using Docker for Mac.
Find my `docker-compose.yml` and `Dockerfile` attached.
How to use the `docker run` flag using `docker-compose.yml`?

```
version: '3.8'

# Networks
# networks:
#  mynet:

# Volumes
volumes:
  mariadbdata:
  phpmyadmindata:

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19.4-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - phpmyadmindata:/var/www/phpmyadmin:ro
    depends_on:
      - php
      - phpmyadmin

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php:cached
      - ./.docker/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini:ro
      - ./.docker/php/magic.mime:/usr/share/magic.mime:ro
    depends_on:
      - mariadb

  # MariaDB Service
  mariadb:
    image: mariadb:10.5.7-focal
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mariadbdata:/var/lib/mysql
      - ./.docker/data-init:/docker-entrypoint-initdb.d:ro

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:5.0.4-apache
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mariadb,mariadb
      PMA_PORTS: 3306,3306
      UPLOAD_LIMIT: 2048G
    volumes:
      - phpmyadmindata:/var/www/html:cached
      - ./.docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    depends_on:
      - mariadb

```

```
FROM php:8.0.0RC3-fpm-alpine3.12

RUN docker-php-ext-install mysqli pdo_mysql
```
