### ISSUE TITLE
apache2: Could not open configuration file /etc/apache2/apache2.conf: No such file or directory

### ISSUE THREAD

**Issue by cbatista8a** [docker-library/php#1084]
path /etc/apache2/ is not mounted on my local folder apache2 for custom configurations
-sites folder is mounted but not apache dir, or the content of /etc/apache2/ on container is erased because my local folder apache2 is empty?

MAC OS High Sierra 10.13.6 (17G14033)

[My docker-compose.yml]

version: "3.8"
services:
  lamp:
    image: "php:7.3-apache"
    volumes:
      - ./sites:/var/www/html
      - ./apache2:/etc/apache2
    ports:
      - 80:80

**Comment by wglambert** [comment]
If you're bind-mounting an empty directory on the host then it will overwrite the target directory

You could use a Docker named volume instead to persist that folder:
```yaml
version: "3.8"
services:
  lamp:
    image: "php:7.3-apache"
    volumes:
      - ./sites:/var/www/html
      - apache2:/etc/apache2
    ports:
      - 80:80

volumes:
  apache2:
```

Or you could copy the contents of a populated `/etc/apache2` directory and then configure and mount that from the host
```console
$ docker run -d --rm --name apache  php:7.3-apache
0ad94e9929feddf2fc852d91527257020cbd6a4c8ba7ed0a820e90c14c30df4f

$ docker cp apache:/etc/apache2 ./apache2

$ ls apache2
apache2.conf     conf-enabled     magic            mods-enabled     sites-available
conf-available   envvars          mods-available   ports.conf       sites-enabled
```
