### ISSUE TITLE
Call program via exec() from nginx+php:fpm

### ISSUE THREAD

**Issue by mikldk** [docker-library/php#1150]
Thanks for your effort. I am not sure that I ask the right place (I have also tried at rocker-org/rocker#453), but I cross my fingers:

I am new in the docker world. For fun, I am trying to make a webserver (nginx + PHP) where I can call an external program from PHP. More specifically, I want to call [R](https://www.r-project.org/) via the `rocker` [r-base](https://hub.docker.com/_/r-base) image.

I have a `docker-compose.yml` containing:

```
version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    r-base:
      image: rocker/r-base:latest
    php:
        image: php:fpm
        volumes:
            - ./app:/app
```

And `app/public/index.php` contains
```
<?php
$test = exec('R --vanilla --quiet --no-save -e "2+2;"');
var_dump($test);
```
As a result I get ` string(0) "" ` and at the console I get 

```
php_1    | sh: 1: R: not found
```

If I in `index.php` instead tries `exec('ls -l /usr/bin')` I don't see R. I am not really sure how to expose R for PHP.

So it seems like the `R` program is not exposed to the `php` service/container. I am not sure if this is correctly inferred - and what to do about it. Does anyone have any suggestions?
