### ISSUE TITLE
docker-php-ext-install fail on new Alpine3.15 base images

### ISSUE THREAD

**Issue by Gytree** [docker-library/php#1269]
Hi folks, I have the next issue with the last Alpine3.15 version
On the next Dockerfile that use the latest alpine version:
```Dockerfile
FROM php:7.4-fpm-alpine
RUN apk update && apk add freetype-dev \
        jpeg-dev \
        libpng-dev \
        libwebp-dev \
        libzip-dev nginx
RUN docker-php-ext-install bcmath mysqli zip
RUN docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype && docker-php-ext-install -j$(nproc) gd
```

The mysqli extension isn't added to the loaded modules, is missing on the `php -m` output. But if i force the alpine version to the 3.14 it works as expected.  using :

```dockerfile
FROM php:7.4-fpm-alpine3.14
```

maybe related [docker-php-ext-installer-issue](https://github.com/mlocati/docker-php-extension-installer/issues/362)?

**Comment by wglambert** [comment]
Sounds like https://github.com/docker-library/wordpress/issues/635#issuecomment-916281427

**Comment by Gytree** [comment]
I'm using `docker-compose` like

```yaml
version: '3'
services:
  php:
    build:
      context: "."
    volumes:
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../html:/var/www/html
      - ./nginx.conf:/etc/nginx/http.d/default.conf
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
```
and the docker file:
```dockerfile
FROM php:7.4-fpm-alpine
RUN apk update && apk add freetype-dev \
	jpeg-dev \
	libpng-dev \
	libwebp-dev \
	libzip-dev nginx
RUN docker-php-ext-install bcmath mysqli zip
RUN docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype && docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-configure pdo && docker-php-ext-install pdo
RUN docker-php-ext-configure pdo_mysql && docker-php-ext-install pdo_mysql
EXPOSE 80
RUN ln -sf /dev/stdout /var/log/nginx/access.log  && ln -sf /dev/stderr /var/log/nginx/error.log
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN apk add vim gcc make autoconf libc-dev \
 && pecl install xdebug && docker-php-ext-enable xdebug
RUN apk add nodejs npm && npm i -g yarn
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN addgroup -g 1000 gytree && adduser -H -D -u 1000 -G gytree -s /bin/sh gytree
COPY entrypoint.sh /
RUN chmod u+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```
