### ISSUE TITLE
*.ini for php in conf.d and php.ini in php folder are not took in count for version 5.6.40-apache

### ISSUE THREAD

**Issue by grimpows** [docker-library/php#1284]
phpinfo dont modify in any way with a file set in the specified folder from doc.
note with exactly same setup but with php 7.4.28-apache, change in the .ini are took in count,
using exactly same dockerfile.

dockerfiles content :
```dockerfile
ARG PHP_VERSION=""
ARG COMPOSER_VERSION=""

FROM php:${PHP_VERSION}-apache

RUN apt-get -qqy update; \
    apt-get -qqy upgrade;

RUN apt-get -qqy install libicu-dev libpng-dev git zip unzip

RUN docker-php-ext-configure intl && docker-php-ext-install intl

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

RUN docker-php-ext-install gd

RUN a2enmod rewrite
```

compose content : 
```yaml
version: '3.8'
services:
  apache-php:
    build:
      context : ${DOCKERFILE_CONTEXT_PATH}/apache-php
      args:
        PHP_VERSION: ${PHP_VERSION}
    expose:
      - 80
    volumes:
      - "${APACHE_SRC}:/var/www/html"
      - "${DOCKERFILE_CONFIGURATION_HOST_PATH:-./../}/apache-php/conf/${PHP_INI_FILENAME:-php/php.ini-development.exemple}:/usr/local/etc/php/php.ini"
```

// skipping useless other YML info for this issue
