### ISSUE TITLE
npm not found

### ISSUE THREAD

**Issue by welly** [docker-library/php#1402]
I'm having a problem in that Robo fails on:

$tasks[] = $this->taskExec('npm install cypress@9 --save-dev');

reporting npm not being found. Also adding `which npm` to the bitbucket cypress step doesn't report finding anything, whereas it does find node:

```
    - step: &cypress-tests
        name: 'Cypress.IO'
        services:
          - mariadb
        script:
          - sleep 10
          - which node
          - which npm
          - robo job:build
          - vendor/bin/robo job:serve-drupal
          - vendor/bin/robo job:cypress-tests

```

Wondered if anyone had any suggestions?
