### ISSUE TITLE
Dockerfile [php:8.2.6-fpm-bullseye] not working

### ISSUE THREAD

**Issue by Mr-Lion** [docker-library/php#1408]
Hi,

I have a problem with my Dockerfile.
I would like to start the image that is described in more detail in the title on my Windows 10 Enterprise system using Docker-Compose. But no matter what I've tried, it doesn't work. As soon as I use an older PHP version of Debian, it works. That means it must be due to the current faulty image.

My Dockerfile looks like this:

```
FROM php:8.2.6-fpm-bullseye

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    vim \
    unzip
```

And my docker-compose file like this:
```
version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-app
    restart: always
    # working_dir: /var/www/
    # volumes:
    #   - ../app:/var/www
  
  nginx:
    image: nginx:latest
    container_name: nginx-srv
    restart: always
    ports:
      - "8080:80"
    # volumes:
    #   - ../app:/var/www
    #   - ./nginx:/etc/nginx/conf.d
```

Here is a screenshot of the whole process and the error message:

![image](https://github.com/docker-library/php/assets/6929357/4ad41566-f35d-4328-8ed0-3b8f4d95bb49)

I list what I use here:
Windows 10 Enterprise (all updates have been made)
Docker Desktop (version 4.19.0)
Hyper-V (also the latest version)
VSCode Editor (version 1.78)
I start the Docker-Compose file in the terminal of VSCode Editor.

I would be very grateful if someone could help me here and possibly fix these errors.

I thank you in advance.

Best regards
