### ISSUE TITLE
Php.ini never apply in php-8.1-apache arm

### ISSUE THREAD

**Issue by lenoira** [docker-library/php#1409]
"The PHP.ini has the correct permissions 644 in /usr/local/etc/php/PHP.ini. The issue does not occur on the php-fpm image nor on the php-8.1-bullseye image. The PHP.ini is never taken into account."

**Comment by lenoira** [comment]
Thanks for your help

My problème is just on the php.ini i want change the post_max_size = 500M. I have copy the php.ini "php.ini-production" more


My configuration:

docker-compose-arm.yml
`version: '3'
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
    front:
      build:
          context: ${GLOBAL_PATH}/dockerconf/front/.
          dockerfile: ./Dockerfile-arm
      expose:
        - 80
        - 443
      volumes:
        - ${GLOBAL_PATH}/front:/app
        - ${GLOBAL_PATH}/data/data:/app/public/data
        - ${GLOBAL_PATH}/haproxy/dockerconf/front/php.ini:/usr/local/etc/php/php.ini
        - ${GLOBAL_PATH}/haproxy/dockerconf/front/customphp.ini:/usr/local/etc/php/conf.d/customphp.ini
        - ${GLOBAL_PATH}/haproxy/dockerconf/front/sites-available:/etc/apache2/sites-available
        - ${GLOBAL_PATH}/haproxy/dockerconf/certs/test.evz.crt:/etc/ssl/certs/xxxxxxxx.crt
        - ${GLOBAL_PATH}/haproxy/dockerconf/certs/test.evz.key:/etc/ssl/private/xxxxxx.key
      #command: sh -c "chown -R root:root /app"
      links:
        - database
      environment:
        PHP_DISPLAY_ERRORS: 1
        WEB_DOCUMENT_ROOT: /app/public
        APACHE_LOG_DIR: /var/log/apache2
        WEB_SERVER_NAME: xxxxxxx`

**Dockerfile-arm**
`FROM php:8.1-apache

# add some build tools
RUN apt-get update && \
    apt-get install -y --force-yes \
	curl \
    zip \
    git \
    vim \
    wget

# COMPOSER v2
RUN wget https://getcomposer.org/download/latest-2.x/composer.phar
RUN mv composer.phar /usr/local/bin/composer
RUN chmod 755 /usr/local/bin/composer

# NODE & NPM
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y --force-yes \
    build-essential \
    nodejs

#enable module php
RUN docker-php-ext-install mysqli pdo_mysql exif

#enable module apache
RUN a2enmod rewrite headers expires ssl

#enable vhost https
RUN a2ensite default-ssl.conf`

**Comment by lenoira** [comment]
Thanks for your help

My problème is just on the php.ini i want change the post_max_size = 500M. I have copy the php.ini "php.ini-production" more my option post_max_size.

No problème on image php:8.1-apache-bullseye. I precise i use the arm image on Mac M2.

My configuration:

docker-compose-arm.yml
```
version: '3'
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
    front:
      build:
          context: ${GLOBAL_PATH}/dockerconf/front/.
          dockerfile: ./Dockerfile-arm
      expose:
        - 80
        - 443
      volumes:
        - ${GLOBAL_PATH}/front:/app
        - ${GLOBAL_PATH}/data/data:/app/public/data
        - ${GLOBAL_PATH}/haproxy/dockerconf/front/php.ini:/usr/local/etc/php/php.ini
        - ${GLOBAL_PATH}/haproxy/dockerconf/front/customphp.ini:/usr/local/etc/php/conf.d/customphp.ini
        - ${GLOBAL_PATH}/haproxy/dockerconf/front/sites-available:/etc/apache2/sites-available
        - ${GLOBAL_PATH}/haproxy/dockerconf/certs/test.evz.crt:/etc/ssl/certs/xxxxxxxx.crt
        - ${GLOBAL_PATH}/haproxy/dockerconf/certs/test.evz.key:/etc/ssl/private/xxxxxx.key
      #command: sh -c "chown -R root:root /app"
      links:
        - database
      environment:
        PHP_DISPLAY_ERRORS: 1
        WEB_DOCUMENT_ROOT: /app/public
        APACHE_LOG_DIR: /var/log/apache2
        WEB_SERVER_NAME: xxxxxxx
```

**Dockerfile-arm**
```
FROM php:8.1-apache

# add some build tools
RUN apt-get update && \
    apt-get install -y --force-yes \
	curl \
    zip \
    git \
    vim \
    wget

# COMPOSER v2
RUN wget https://getcomposer.org/download/latest-2.x/composer.phar
RUN mv composer.phar /usr/local/bin/composer
RUN chmod 755 /usr/local/bin/composer

# NODE & NPM
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y --force-yes \
    build-essential \
    nodejs

#enable module php
RUN docker-php-ext-install mysqli pdo_mysql exif

#enable module apache
RUN a2enmod rewrite headers expires ssl

#enable vhost https
RUN a2ensite default-ssl.conf
```
