### ISSUE TITLE
php:7-apache

### ISSUE THREAD

**Issue by huglester** [docker-library/php#214]
Hello,

I don't understand one simple thing, I am runing from:

```yml
db:
    image: mysql
    ports:
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: root
        MYSQL_PASSWORD: root

web:
    image: php:7.0.4-apache
    ports:
        - "81:80"
    volumes:
        - ./:/var/www/html/
    links:
        - db:db
```
the problem is, that I have ./public - as the docroot. 
in this scenario /var/www/html is the docroot for apache.

I could link ./ to ./var/www
but again, I need /public instead of /html.. Any ideas? Or the only way to create my own 'fork' and edit?

Thank you
