### ISSUE TITLE
How to link custom apache2 config

### ISSUE THREAD

**Issue by cwrm** [docker-library/php#232]
Hi, I have built a container with a Dockerfile from php:5.5.35-apache. I wonder where I have to place my apache2 conf Files with aliases, DocumentRoot and so on.

When I copy my conf to `/etc/apache2/sites-enabled/` the container fails to start.

ciao
chris

**Comment by Eyal-Shalev** [comment]
@cwrm Have you found a solution to this problem?

I'm having the exact same issue and found no correct solution.

Here are a few of my failed attempts:
* Mark the sites-enabled as a volume directory (in docker-compose.yml)
* 
 1. Set a custom directory in /etc/apache2 as a volume (in docker-compose.yml)
 2. Include the custom directory by adding a custom IncludeOptions command in /etc/apache2/apache2.conf file

**Comment by yosifkit** [comment]
Can you share your Apache and docker-compose files? Perhaps you have a custom log directive pointing outside the `APACHE_LOG_DIR`?

**Comment by Eyal-Shalev** [comment]
### docker-compose.yml
```
version: '2'
services:
    web:
        image: eyalshalev/php:apache
        ports:
            - "80:80"
        volumes:
            - "./docroot:/var/www/html"
            - "./apache2/vhosts:/etc/apache2/from-host"
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sandbox
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8009:8009"
    composer:
        image: composer/composer
        volumes_from:
            - web
        working_dir: /var/www/html
```

### Dockerfile (eyalshalev/php:apache)
```
FROM php:7.0-apache

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

 RUN mkdir -p  /etc/apache2/from-host

 RUN echo "" >> /etc/apache2/apache2.conf \
	&& echo "# Include the configurations from the host machine" >> /etc/apache2/apache2.conf \
	&& echo "IncludeOptional from-host/*.conf" >> /etc/apache2/apache2.conf
```
