### ISSUE TITLE
You need to enable the PDO_Mysql extension for Phinx to run properly.  

### ISSUE THREAD

**Issue by rajjejosefsson** [docker-library/php#309]
When I'm trying to do a migration to my mysql server i get the following exception:

```
 [RuntimeException]                                                     
  You need to enable the PDO_Mysql extension for Phinx to run properly.  


```

**Dockerfile**

```
FROM php:7.0-fpm

RUN docker-php-ext-install pdo_mysql
```

**docker-compose.yml**

```
nginx:
    build: ./nginx/
    ports:
        - 8080:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app


composer:
    image: composer/composer
    volumes_from: 
        - app

app:
    image: php:7.0-fpm
    volumes:
        - .:/var/www/html
    command: "true"

mysql:
    image: mysql:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: rshop
        MYSQL_USER: root
        MYSQL_PASSWORD: secret

data:
    image: mysql:latest
    volumes:
        - /var/lib/mysql
    command: "true"


phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8888:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
```
