### ISSUE TITLE
Folder ownership modified to root when bind-mounting named-volumes

### ISSUE THREAD

**Issue by tomfotherby** [docker-library/php#396]
Steps to reproduce:

1. As a non-root user, create a junk folder and cd to it:  `mkdir junk;cd junk`
1. Create a `docker-compose.yml` file in the new folder that uses a php image with a named-volume bind-mounted to the current folder.

    ```
    version: '2.0'

    services:
      myapp:
        image: php:7.0-fpm
        volumes:
          - myvol:/var/www

    volumes:
      myvol:
        driver_opts:
          type: none
          device: $PWD
          o: bind
    ```
1. Execute php-fpm: `docker-compose up -d` (It will fail with a error message but that doesn't matter because the bug is still exposed)
1. Check folder ownership: `ls -ld`
1. Notice, it's been changed from your user to `root`.

This bug means my working folder keeps being reset to `root` ownership which breaks things like `git`.

The bug doesn't happen when not using "named volumes". So the simple workaround is:

```
version: '2.0'

services:
  myapp:
    image: php:7.0-fpm
    volumes:
      $PWD:/var/www
```
But it's a shame not to use "named volumes" because when you do `docker volume ls` you just see a hash and have no idea what the volume is for.

I noticed if I use a different docker image in the `docker-compose.yml` file , e.g. `alpine`, or `busybox` or `debian:jessie` , then the folder ownership is not changed, so the issue is something to do with the `php:7.0-fpm` image. Also if you bind-mount to something random like `/bob` instead of `/var/www` the permissions are also not changed, so it seems fpm is picking on document root folders (`/var/www`).

---

```
$ docker -v
Docker version 17.03.0-ce, build 60ccb22
$ docker-compose -v
docker-compose version 1.12.0-rc1, build 5e0a793
```

Docker php image: `php:7.0-fpm`
