### ISSUE TITLE
Custom/parametrized port for fpm

### ISSUE THREAD

**Issue by bsramin** [docker-library/php#479]
Would not it be convenient to handle the fpm port (9000) in a custom way? So on compose or on run you can start it with the port we prefer. You would avoid conflicts with xdebug and you could start multiple fpm services on the same web server...

**Comment by yosifkit** [comment]
Each FPM running in its own container will not have a port conflict with any other FPM running on the server.  There are two ways to handle them.

Run a load balancer like Nginx to proxy to the correct FPM container; this would access each FPM via its container IP at port 9000.  This works great since you have to run something that speaks the FPM protocol in order to serve any web requests.  This can easily be spread over multiple machines with Docker Swarm mode.  This would also prevent any of the FPM ports from being potentially publicly accessible.

Alternatively, with compose you can just map a different host port to the container port.  Note that you would still need to run something like Nginx in order to route web requests to the FPM service.

```yaml
# this would make this FPM service available at port 9001 on the Docker host
  ports:
    - "9001:9000"

# or let Docker choose a high unused port like 32768 to use on the host
  ports:
    - "9000"
```
