### ISSUE TITLE
Add init scripts execution

### ISSUE THREAD

**Issue by iBobik** [docker-library/php#529]
I often need to run some scripts before daemon startup and much simpler than overriding entrypoint will be to just COPY my script to image and this script will be automatically executed.

Something like this in `docker-php-entrypoint`:

```diff
  #!/bin/sh
  set -e
  
+ # Execute all init scripts
+ if [ -d /init.d ]; then
+ 	for f in /init.d/*.sh; do
+ 		bash "$f"
+ 	done
+ fi
+ 
  # first arg is `-f` or `--some-option`
  if [ "${1#-}" != "$1" ]; then
  	set -- apache2-foreground "$@"
  fi
  
  exec "$@"
```

Then custom `Dockerfile` can contain something like this:
```
COPY scripts/wait_for_db.sh /init.d/1_wait_for_db.sh
```

Is PR wellcome?

**Comment by bweston92** [comment]
Do we have any other use cases then just waiting for a socket?

**Comment by iBobik** [comment]
Yes, I use it for db initialization and schema upgrade also. Lately used something similar for conditional enabling xdebug extension.

**Comment by yosifkit** [comment]
The `initdb` support in images like MariaDB and MySQL was added specifically because the functionality provided there can't be duplicated in a Dockerfile, `docker run`, or compose yaml easily.  This addition is something that is possible in all three cases.

Compose examples:
```yaml
version: "3"

services:
  web:
    image: php:7.2-apache-stretch
    volumes:
      - ./scripts/:/init-scripts/
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'running prestart script'
        /init-scripts/prestart.sh
       
        echo 'running init.php'
        php -f /init-script/some/init.php
        
        echo 'initialization done, starting apache'
        exec apache2-foreground

# alternatively
  web2:
    image: php:7.2-apache-stretch
    volumes:
      - ./scripts/:/init-scripts/
    command:
      - /init-scripts/custom-script.sh
# where the custom-script.sh can run other scripts in the folder
# and then end with "exec apache2-foreground"
```

A dockerfile:
```Dockerfile
FROM php:7.2-apache-stretch
COPY ./scripts/ /init-scripts/
CMD /init-scripts/custom-script.sh
# where the custom-script.sh can run other scripts in the folder
# and then end with "exec apache2-foreground"
```

On a docker run line:
```console
$ docker run -d -v "$PWD"/scripts/:/init-scripts/ php:7.2-apache-stretch /init-scripts/custom-script.sh
```

Similar/related issues: https://github.com/docker-library/rabbitmq/issues/5, https://github.com/docker-library/wordpress/issues/147
