### ISSUE TITLE
Getting "ERROR: Service 'coffee-web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder924859935/docker-php-source: no such file or directory""

### ISSUE THREAD

**Issue by RoestVrijStaal** [docker-library/php#671]
Hi all,

I get "ERROR: Service 'coffee-web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder924859935/docker-php-source: no such file or directory" when running `docker-compose up`

My _docker-compose.yml_

```yml
version: "3.1"

services:
  coffee-web:
    container_name: coffee-web
    image: php:7.2-apache
    build: ./docker/web/
    ports:
     - "80:80"
    volumes:
     - ./:/var/www
    links:
     - coffee-db:db.dev.wcoffee.nl
  coffee-db:
    container_name: coffee-db
    image: mysql:latest
    build: ./docker/db/
    ports:
     - "3306:3306"
    volumes:
     - ./data/db:/var/lib/mysql
     - ./docker/db/data:/docker-entrypoint-initdb.d
```

_Dockerfile_ of use: in _./docker/web_ https://github.com/docker-library/php/blob/cff4da8fdbf0461c855a63d18431e18eed4cbcdc/7.2/stretch/apache/Dockerfile

Why is this going wrong?
