### ISSUE TITLE
alpine fpm image does not support running as a different user other than www-data

### ISSUE THREAD

**Issue by vogelfreiheit** [docker-library/php#876]
This has been mentioned (and evidenced) in #70 and #14, and the presence of hardcoded usernames already affected the apache images (see docker-library/wordpress#249).

Multiple longstanding issues exist, including some in the doc repo: https://github.com/docker-library/docs/pull/1215#issue-186709467. It seems the apache images are working now with this, although the fpm ones are not. This is unfortunate as the memory footprint of fpm is far lower, it is easier to isolate vs mod_php, and it does not create a en entire copy of the PHP interpreter and libraries *in memory* for every web server process. 

I find it puzzling that the fpm images did not benefit from this first, as the ease of implementing this feature for them should be slightly more simple than it was for the apache counterparts.

@rcdailey has contributed quite a bit for this, AFAIK, but I don't see anything merged or working in the main repos.

See also https://github.com/nextcloud/docker/issues/458#issue-359431933

**Comment by rcdailey** [comment]
The downside to fpm is that you have to expose paths inside the Nextcloud
container to the container for the reverse proxy. I personally found the
setup for that was pretty complicated and ugly. And honestly the
performance is really good without it.

**Comment by vogelfreiheit** [comment]
```
  nextcloud-app:
    image: nextcloud:16-apache
    restart: unless-stopped
    user: $NEXTCLOUD_WEB_UID:$NEXTCLOUD_WEB_GID
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    environment:
      - MYSQL_HOST=nextcloud-db
      - APACHE_RUN_USER=#$NEXTCLOUD_WEB_UID
      - APACHE_RUN_GROUP=#$NEXTCLOUD_WEB_GID
      - NEXTCLOUD_DATA_DIR=/nextcloud-data
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=(...)
    env_file:
      - db.env
    volumes:
      - nextcloud-web:/var/www/html
      - nextcloud-data:/nextcloud-data
    ports:
      - 127.0.0.1:8082:80
```

No dice. Not sure fpm, it shouldn't be the case unless you chroot the fpm pool process.
Definitely not having a lucky strike with the docker composer files for nextcloud. 

Also seeing this:
```
nextcloud-app_1    | Configuring Redis as session handler
nextcloud-app_1    | /entrypoint.sh: 26: /entrypoint.sh: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied
nextcloud-app_1    | Initializing nextcloud 16.0.4.1 ...
nextcloud-db_1     | Initializing database

```
