### ISSUE TITLE
php:7.3.10-apache-stretch +Symfony cause 404

### ISSUE THREAD

**Issue by darkiron** [docker-library/php#899]
Hi, 
I use php:7.3.10-apache-stretch to serve with Symfony 4.
My docker-compose : 
```
php: 
    image: php:7.3.10-apache-stretch
    ports:
      - "8888:80"
    volumes:
     # - ./back/public:/var/www/html
      - ./back:/var/www/html
      - ./apache/logs:/var/log/apache2
      #- ./apache/conf:/etc/apache2/conf-available
      #- ./apache/conf/default.conf:/etc/apache2/sites-available/default.conf
      - ./apache/conf:/etc/apache2/sites-available/
    #environment:
    #  APACHE_DOCUMENT_ROOT: /public
    links:
      - sql
    networks: 
      - internal
```

vhost use : 
```
<VirtualHost *:80>
    #ServerName domain.tld
    #ServerAlias www.domain.tld
    
    DocumentRoot /var/www/project/public
    DirectoryIndex /index.php

    <Directory /var/www/project/public>
        AllowOverride None
        Order Allow,Deny
        Allow from All

        FallbackResource /index.php
    </Directory>
    
    ErrorLog /var/log/apache2/project_error.log
    CustomLog /var/log/apache2/project_access.log combined
</VirtualHost>
```

I have a root: 
/login

when I try to access this route have 404. I didin't understand why. 
Log is not explicit
Juste access error: 
172.30.0.1 - - [10/Oct/2019:15:18:47 +0000] "GET /index.php HTTP/1.1" 404 500 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

Thanks for your help
