### ISSUE TITLE
Run docker-php-ext-configure causes: Error processing tar file: unexpected EOF

### ISSUE THREAD

**Issue by hieunv-0998** [docker-library/php#974]
**TL;DR:** 
`RUN docker-php-ext-configure` with a newline causes a failed build.
```
ERROR: Service 'php-fpm' failed to build: Error processing tar file(exit status 1): unexpected EOF
```

**Steps to produce:**
1. Create a Dockerfile, which using docker-php-ext-configure with a newline.
 `./project/.docker/php-fpm/Dockerfile`
```Dockerfile
FROM php:7.3-fpm-stretch

RUN apt-get update -yqq && \
    apt-get install -y zlib1g-dev libicu-dev g++

RUN docker-php-ext-configure intl

RUN docker-php-ext-install intl
```
2. Build a new container from above image with docker-compose.
```yaml
version: "3"
services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./project/.docker/php-fpm/
    volumes:
      - ./project:/var/www/project
    expose:
      - "9000"
```
3. Run `docker-compose` build command.
```
docker-compose up -d --build php-fpm
```
Build fails when execute line: `RUN docker-php-ext-configure intl`
```
Step 2/3 : RUN docker-php-ext-configure intl
 ---> Running in 80f9be8368da
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
....
....
creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
ERROR: Service 'php-fpm' failed to build: Error processing tar file(exit status 1): unexpected EOF
```

**How to fix (in my way)**
Append an other command into command `RUN docker-php-ext-configure`
```Dockerfile
RUN docker-php-ext-configure intl && \
    docker-php-ext-install intl
```

I hope this share that helps some person who also is struggling this kind of issue.
But I expect that someone can help me explain why this odd happens, too.
